### ISSUE TITLE
installer.py issues

### ISSUE THREAD

**Issue by mrmustard69** [ckamte/adobe-packager-windows#1]
=================================
=     Build Adobe Installer     =
============= 1.0.0 =============

Traceback (most recent call last):
  File "C:\adobe packager\installer.py", line 271, in <module>
    get_packages()
  File "C:\adobe packager\installer.py", line 114, in get_packages
    setupVersion = setup_version()
                   ^^^^^^^^^^^^^^^
  File "C:\adobe packager\installer.py", line 64, in setup_version
    return json.loads(jsonFromPowerShell)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mrmustard69** [comment]
When I changed the destination directory,  the installer.py worked.

**Comment by ckamte** [comment]
> When I changed the destination directory, the installer.py worked.

Thank you for testing.
Space in folder path cause this error. Now it will work.

**Comment by mrmustard69** [comment]
I found that you need some CC files for the setup.exe to work after you run
the installer.py.
Copy the files & directories in c:\Program Files(86)\Common
FIles\Adobe\Adobe Desktop Common from an installed system.

Also, you don't need the resources folder in your distribution - just have
the ccdl-win.py, installer.py, setup.zips and readme.

I have 2 suggestions - after setup.exe is run, have the option to run the
program or quit. It runs the program automatically.
It would be nice to leave out some of the downloaded files during
installation.

Thanks for your efforts!
