### ISSUE TITLE
Working Set-up tutorial?

### ISSUE THREAD

**Issue by Morku** [ckamte/adobe-packager-windows#2]
Hi,

thank you for the great project. Downloading with ccdl-win.py works like a charm.

Now I wanted to create a working Set-up.exe and followed the steps with `Create manually`. My testing application is `Adobe Bridge 14.0.3`. I used default setting when downloading (v6, win64, KBRG, 14.0.3.200, de_DE).
I followed the steps and started `Set-up.exe 5.2.0.436`. The Install Pop-up with Adobe Bridge appears fine. As I press continue I get `Errorcode: 41`. "Issue to access some important files".
So I checked how the creation compares to other Repacks.
I noticed that files from folder `packages` are still in a zip (e.g. \packages\ADC\ADS\ADS.zip) while other repacks are extracted into .pima .pimx and in .sig files.
I extracted every packages, respecting folder structure so that `ApplicationInfo.xml` points to correct file (e.g. /packages/AAM/IPC/IPC.pimx).

Now when I run Set-up.exe and click Continue I gett `Errorcode: 4`. "There are errors in downloaded files." Looking up that errorcode doesn't show up anything useful.
I can't find any other differences and don't know how to fix it.

Can you advise the missing part? Is the Creative Cloud mandatory that I don't have installed to make it installing? Thank you.

**Comment by ckamte** [comment]
Hi @Morku 

Please try this version again. Its work for me.
You will need to delete downloaded zip file manually.

**Comment by Morku** [comment]
Hi,

I can confirm that the installer now extract all zip files. However, it does not solve the issue, that running Set-up.exe fails with Errorcode 4. When you press Quit on that Error dialog, you get an endless loading circle and need to kill task.

**Comment by ckamte** [comment]
Hi,

It seem path string error (slash vs backslash) in applicationinfo.xml file.
Heres a working file.
[ApplicationInfo.zip](https://github.com/ckamte/adobe-packager-windows/files/14864926/ApplicationInfo.zip)

**Comment by Morku** [comment]
I can confirm, installation works fine now :)
I didn't notice the difference in slash/backslash myself.

It also installed all the Cloud bloat. At this point I can check and modify myself to minimize the amount of data.

Thank you very much!

**Comment by ckamte** [comment]
Thank you for testing. I updated installyer.py with correct path string. :)

**Comment by ckamte** [comment]
> I can confirm, installation works fine now :) I didn't notice the difference in slash/backslash myself.
> 
> It also installs all the Cloud bloat. At this point I can check and modify myself to minimize the amount of data.
> 
> Thank you very much!

Heres minimal pakages.

[ApplicationInfo_min.zip](https://github.com/ckamte/adobe-packager-windows/files/14865126/ApplicationInfo_min.zip)
