### ISSUE TITLE
PPRO 23 wont build installer

### ISSUE THREAD

**Issue by treatmeniceplz** [ckamte/adobe-packager-windows#6]
it just errors out if you want the error itself i can post it here

**Comment by ckamte** [comment]
Which version of setup.exe file?
Seeing all error would be great.

**Comment by treatmeniceplz** [comment]
Both v5 and v6

**Comment by ckamte** [comment]
Cannot create installer or cannot install?

**Comment by treatmeniceplz** [comment]
Can't create it

**Comment by ckamte** [comment]
`=================================
=     Build Adobe Installer     =
============= 1.1.0 =============


Get Required packages for Adobe Installer v-6.1.0.587

Downloading package: IPC
100%|███████████████████████████████████████████████████████████████████████████████████████████| 642k/642k [00:00<00:00, 2.32MiB/s]
Extracting provapp-IPC.zip contents
...
Downloading package: Lightroom
100%|███████████████████████████████████████████████████████████████████████████████████████████| 560k/560k [00:00<00:00, 1.27MiB/s] 
Extracting Lightroom.zip contents

Creating ApplicationInfo.xml

Getting AdobePIM.dll

Successfully downloaded installer files`

**Comment by treatmeniceplz** [comment]
Yea I don't get that far

**Comment by ckamte** [comment]
Show me error.

**Comment by treatmeniceplz** [comment]
Can I send it tommorow afternoon

**Comment by ckamte** [comment]
Ok.

**Comment by monitor22** [comment]
latest photoshop got blank screen on the installation page when downloading All language version. English only works fine tho.,
![2024-11 22_02_25](https://github.com/user-attachments/assets/8dcdeec8-b697-4244-bdcd-fe9b42b022da)

**Comment by treatmeniceplz** [comment]
![image](https://github.com/user-attachments/assets/a6ea7b9d-5594-423b-ad77-a57bc12dd405)

**Comment by ckamte** [comment]
Hi @treatmeniceplz,

It seems power-shell error.
I think your "Set-up.exe" file is missing or corrupt. Did you extract Set-up.exe from zip file?

**Comment by treatmeniceplz** [comment]
I extracted the whole zip file as far as I'm aware

**Comment by treatmeniceplz** [comment]
Must of corrupted somehow

**Comment by ckamte** [comment]
Please test this in your power shell

```YOUR-FILE-LOCATION>(Get-Item .\Set-up.exe).VersionInfo.FileVersion``

**Comment by treatmeniceplz** [comment]
managed to reproduce what you got 
![image](https://github.com/user-attachments/assets/27316fed-eaf4-411f-806d-41168693d2eb)

**Comment by treatmeniceplz** [comment]
here is a better screenshot
![image](https://github.com/user-attachments/assets/67e3bc06-c874-4501-a288-323c9a5c03dd)

**Comment by ckamte** [comment]
Put your Set-up.exe and build_installer.py in same folder.

**Comment by ckamte** [comment]
Hi @monitor22,

I don't know what cause this. But removing

<Language locale="id_ID" />

(Indonesian language)
line from Driver.xml work.

**Comment by treatmeniceplz** [comment]
> Put your Set-up.exe and build_installer.py in same folder.

that fixed it
seems like im not finished with this code yet as i need to fix the issue that started this github issue

**Comment by ckamte** [comment]
@treatmeniceplz
Thank you for testing.
